### ISSUE TITLE
Define formalization of simulated pod spec

### ISSUE THREAD

**Issue by ordovicia** [pfnet-research/k8s-cluster-simulator#5]
EDIT: changed to use YAML https://github.com/ordovicia/k8s-cluster-simulator/issues/5#issuecomment-446137859

---

Temporarily specified by embedding a ~JSON~ string as an annotation.

```yaml
metadata:
  name: nginx-sim
  annotations:
    simSpec: "[{\"seconds\":5,\"cpu\":\"1\",\"memory\":\"2Gi\",\"nvidia.com/gpu\":0},{\"seconds\":10,\"cpu\":\"2\",\"memory\":\"4Gi\",\"nvidia.com/gpu\":1}]"
```

- [x] Deterministic
- [ ] Probabilistic

**Comment by ordovicia** [comment]
Changed to use yaml.

```yaml
metadata:
  name: nginx-sim
  annotations:
    simSpec: |
- seconds: 5
  resourceUsage:
    cpu: 1
    memory: 2Gi
    nvidia.com/gpu: 0
- seconds: 10
  resourceUsage:
    cpu: 2
    memory: 4Gi
    nvidia.com/gpu: 1`
```
